language: objective-c

env:
  matrix:
    - MONO_VERSION="3.12.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - brew install redis
  - redis-server /usr/local/etc/redis.conf &

script: 
  - git clone https://github.com/StackExchange/StackExchange.Redis.git
  - cd StackExchange.Redis
  - ./monobuild.bash
  - cd ..
  - ./build.sh All
